version: "3.4"

services:
  postgres:
    container_name: blog_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: blog_db
      POSTGRES_DB: blog_db
      POSTGRES_PASSWORD: blog_db

volumes:
  postgres_data:
